// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Use Press Start 2P via next/font
const pressStart = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  // If you want a CSS var you can reference in CSS, uncomment:
//   variable: "--font-press-start",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Prefer a local icon: put /public/favicon.ico or /app/icon.png
  icons: {
    icon: "/favicon.ico", // or remove this if you add /app/icon.png
    // If you *must* use a remote icon (not recommended):
    // other: [{ rel: "icon", url: "https://your.cdn/icon.png", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pressStart.className} antialiased`}
      >
        {/* If you only want Press Start on certain elements, remove
            `${pressStart.className}` above and add it to those elements instead. */}
        {children}
      </body>
    </html>
  );
}
